# the reason of .dev.....Docker file is only used when we are trying to run our application in a development environment.

FROM node:alpine

WORKDIR  '/app'

COPY package.json .
RUN npm install

COPY . .

CMD ["npm", "run", "start"]
